# Generated by Django 5.1.6 on 2025-03-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='uploaddate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
